### ISSUE TITLE
Link ACM Site

### ISSUE THREAD

**Issue by dnhess** [siggame/acmgame.github.io#22]
We need to add a link to the site to send a user to the acm website. Possibly on the footer of the site.

**Comment by silent-lad** [comment]
I am working on this. @dnhess can you please provide me with more details?

**Comment by dnhess** [comment]
Sure,
The ACM site is the following: https://acm.mst.edu/ 
It was suggested in a meeting that we should have a link back to their site since we are apart of ACM. So my idea would be to include a link back to their site somewhere on our siggame.io website. I figure putting their link inside of our footer underneath "contact us" would be a nice location. The code location for the footer is: 
siggame.github.io/_includes/footer.html

**Comment by silent-lad** [comment]
@dnhess i've made a PR for the same, do tell me if you need any changes.
